version: "1.0"
services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pagos
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"
      

volumes:
  mariadb-data: